name: Extrair Nome da Branch de Origem

on:
  pull_request:
    types:
      - closed

jobs:
  obter-nome-da-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar variáveis de ambiente
      run: |
        PR_URL=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
        BRANCH_NAME=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL | jq -r .head.ref)
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Imprimir o nome da branch de origem
      run: |
        echo "O nome da branch de origem do PR é $BRANCH_NAME"
